ALTER TABLE "xb_companies"
  ADD COLUMN IF NOT EXISTS "primary_color" TEXT NOT NULL DEFAULT '#0ea5e9',
  ADD COLUMN IF NOT EXISTS "secondary_color" TEXT NOT NULL DEFAULT '#0f172a',
  ADD COLUMN IF NOT EXISTS "accent_color" TEXT NOT NULL DEFAULT '#22c55e';
