// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateWorkspaceProbeWorkspaceProbePostData, CreateWorkspaceProbeWorkspaceProbePostErrors, CreateWorkspaceProbeWorkspaceProbePostResponses, GetAuthenticatedUserApiV1AuthMeGetData, GetAuthenticatedUserApiV1AuthMeGetResponses, GetCompanyApiV1CompaniesCompanyIdGetData, GetCompanyApiV1CompaniesCompanyIdGetErrors, GetCompanyApiV1CompaniesCompanyIdGetResponses, GetHealthHealthGetData, GetHealthHealthGetResponses, GetLatestWorkspaceProbeWorkspaceProbeLatestGetData, GetLatestWorkspaceProbeWorkspaceProbeLatestGetResponses, ReceiveClerkWebhookApiV1WebhooksClerkPostData, ReceiveClerkWebhookApiV1WebhooksClerkPostResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Get Authenticated User
 */
export const getAuthenticatedUserApiV1AuthMeGet = <ThrowOnError extends boolean = false>(options?: Options<GetAuthenticatedUserApiV1AuthMeGetData, ThrowOnError>): RequestResult<GetAuthenticatedUserApiV1AuthMeGetResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetAuthenticatedUserApiV1AuthMeGetResponses, unknown, ThrowOnError>({ url: '/api/v1/auth/me', ...options });

/**
 * Get Company
 */
export const getCompanyApiV1CompaniesCompanyIdGet = <ThrowOnError extends boolean = false>(options: Options<GetCompanyApiV1CompaniesCompanyIdGetData, ThrowOnError>): RequestResult<GetCompanyApiV1CompaniesCompanyIdGetResponses, GetCompanyApiV1CompaniesCompanyIdGetErrors, ThrowOnError> => (options.client ?? client).get<GetCompanyApiV1CompaniesCompanyIdGetResponses, GetCompanyApiV1CompaniesCompanyIdGetErrors, ThrowOnError>({ url: '/api/v1/companies/{company_id}', ...options });

/**
 * Receive Clerk Webhook
 */
export const receiveClerkWebhookApiV1WebhooksClerkPost = <ThrowOnError extends boolean = false>(options?: Options<ReceiveClerkWebhookApiV1WebhooksClerkPostData, ThrowOnError>): RequestResult<ReceiveClerkWebhookApiV1WebhooksClerkPostResponses, unknown, ThrowOnError> => (options?.client ?? client).post<ReceiveClerkWebhookApiV1WebhooksClerkPostResponses, unknown, ThrowOnError>({ url: '/api/v1/webhooks/clerk', ...options });

/**
 * Get Health
 */
export const getHealthHealthGet = <ThrowOnError extends boolean = false>(options?: Options<GetHealthHealthGetData, ThrowOnError>): RequestResult<GetHealthHealthGetResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetHealthHealthGetResponses, unknown, ThrowOnError>({ url: '/health', ...options });

/**
 * Create Workspace Probe
 */
export const createWorkspaceProbeWorkspaceProbePost = <ThrowOnError extends boolean = false>(options: Options<CreateWorkspaceProbeWorkspaceProbePostData, ThrowOnError>): RequestResult<CreateWorkspaceProbeWorkspaceProbePostResponses, CreateWorkspaceProbeWorkspaceProbePostErrors, ThrowOnError> => (options.client ?? client).post<CreateWorkspaceProbeWorkspaceProbePostResponses, CreateWorkspaceProbeWorkspaceProbePostErrors, ThrowOnError>({
    url: '/workspace-probe',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Latest Workspace Probe
 */
export const getLatestWorkspaceProbeWorkspaceProbeLatestGet = <ThrowOnError extends boolean = false>(options?: Options<GetLatestWorkspaceProbeWorkspaceProbeLatestGetData, ThrowOnError>): RequestResult<GetLatestWorkspaceProbeWorkspaceProbeLatestGetResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetLatestWorkspaceProbeWorkspaceProbeLatestGetResponses, unknown, ThrowOnError>({ url: '/workspace-probe/latest', ...options });
