// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateWorkspaceProbeWorkspaceProbePostData, CreateWorkspaceProbeWorkspaceProbePostErrors, CreateWorkspaceProbeWorkspaceProbePostResponses, GetHealthHealthGetData, GetHealthHealthGetResponses, GetLatestWorkspaceProbeWorkspaceProbeLatestGetData, GetLatestWorkspaceProbeWorkspaceProbeLatestGetResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Get Health
 */
export const getHealthHealthGet = <ThrowOnError extends boolean = false>(options?: Options<GetHealthHealthGetData, ThrowOnError>): RequestResult<GetHealthHealthGetResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetHealthHealthGetResponses, unknown, ThrowOnError>({ url: '/health', ...options });

/**
 * Create Workspace Probe
 */
export const createWorkspaceProbeWorkspaceProbePost = <ThrowOnError extends boolean = false>(options: Options<CreateWorkspaceProbeWorkspaceProbePostData, ThrowOnError>): RequestResult<CreateWorkspaceProbeWorkspaceProbePostResponses, CreateWorkspaceProbeWorkspaceProbePostErrors, ThrowOnError> => (options.client ?? client).post<CreateWorkspaceProbeWorkspaceProbePostResponses, CreateWorkspaceProbeWorkspaceProbePostErrors, ThrowOnError>({
    url: '/workspace-probe',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Latest Workspace Probe
 */
export const getLatestWorkspaceProbeWorkspaceProbeLatestGet = <ThrowOnError extends boolean = false>(options?: Options<GetLatestWorkspaceProbeWorkspaceProbeLatestGetData, ThrowOnError>): RequestResult<GetLatestWorkspaceProbeWorkspaceProbeLatestGetResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetLatestWorkspaceProbeWorkspaceProbeLatestGetResponses, unknown, ThrowOnError>({ url: '/workspace-probe/latest', ...options });
