// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * ApplicationMetadata
 */
export type ApplicationMetadata = {
    /**
     * Environment
     */
    environment: string;
    /**
     * Name
     */
    name: string;
    /**
     * Version
     */
    version: string;
};

/**
 * DatabaseReadiness
 */
export type DatabaseReadiness = {
    /**
     * Configured
     */
    configured: boolean;
    /**
     * Database
     */
    database?: string | null;
    /**
     * Driver
     */
    driver?: string | null;
    /**
     * Host
     */
    host?: string | null;
    /**
     * Status
     */
    status: 'configured' | 'unconfigured' | 'invalid';
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HealthResponse
 */
export type HealthResponse = {
    application: ApplicationMetadata;
    database: DatabaseReadiness;
    /**
     * Status
     */
    status: 'ok';
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
    /**
     * Input
     */
    input?: unknown;
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * WorkspaceProbeCreateRequest
 */
export type WorkspaceProbeCreateRequest = {
    /**
     * Source
     */
    source: string;
    /**
     * Status
     */
    status?: 'completed';
};

/**
 * WorkspaceProbeResponse
 */
export type WorkspaceProbeResponse = {
    /**
     * Created At
     */
    created_at: string;
    /**
     * Id
     */
    id: number;
    /**
     * Source
     */
    source: string;
    /**
     * Status
     */
    status: 'completed';
    /**
     * Updated At
     */
    updated_at: string;
};

export type GetHealthHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type GetHealthHealthGetResponses = {
    /**
     * Successful Response
     */
    200: HealthResponse;
};

export type GetHealthHealthGetResponse = GetHealthHealthGetResponses[keyof GetHealthHealthGetResponses];

export type CreateWorkspaceProbeWorkspaceProbePostData = {
    body: WorkspaceProbeCreateRequest;
    path?: never;
    query?: never;
    url: '/workspace-probe';
};

export type CreateWorkspaceProbeWorkspaceProbePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateWorkspaceProbeWorkspaceProbePostError = CreateWorkspaceProbeWorkspaceProbePostErrors[keyof CreateWorkspaceProbeWorkspaceProbePostErrors];

export type CreateWorkspaceProbeWorkspaceProbePostResponses = {
    /**
     * Successful Response
     */
    201: WorkspaceProbeResponse;
};

export type CreateWorkspaceProbeWorkspaceProbePostResponse = CreateWorkspaceProbeWorkspaceProbePostResponses[keyof CreateWorkspaceProbeWorkspaceProbePostResponses];

export type GetLatestWorkspaceProbeWorkspaceProbeLatestGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/workspace-probe/latest';
};

export type GetLatestWorkspaceProbeWorkspaceProbeLatestGetResponses = {
    /**
     * Successful Response
     */
    200: WorkspaceProbeResponse;
};

export type GetLatestWorkspaceProbeWorkspaceProbeLatestGetResponse = GetLatestWorkspaceProbeWorkspaceProbeLatestGetResponses[keyof GetLatestWorkspaceProbeWorkspaceProbeLatestGetResponses];
