ALTER TABLE "xb_companies"
  ADD COLUMN IF NOT EXISTS "cover_image_url" TEXT;

ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'COMPANY_COVER_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'COMPANY_COVER_REMOVED';
