ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'ACCOUNTANT';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'APPROVER';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'VIEWER';

ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'USER_INVITED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'USER_CREATED_BY_ADMIN';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'USER_UPDATED_BY_ADMIN';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'USER_DEACTIVATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'USER_REACTIVATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'USER_ROLE_CHANGED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'USER_INVITE_ACCEPTED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'USER_INVITE_REVOKED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'USER_PASSWORD_RESET_SENT_BY_ADMIN';
