ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'CUSTOMER_COVER_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'CUSTOMER_COVER_REMOVED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'CUSTOMER_LOGO_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'CUSTOMER_LOGO_REMOVED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'SUPPLIER_COVER_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'SUPPLIER_COVER_REMOVED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'SUPPLIER_LOGO_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'SUPPLIER_LOGO_REMOVED';
